require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProcessedDataController do

  # This should return the minimal set of attributes required to create a valid
  # ProcessedDatum. As you add validations to ProcessedDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all processed_data as @processed_data" do
      processed_datum = ProcessedDatum.create! valid_attributes
      get :index
      assigns(:processed_data).should eq([processed_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested processed_datum as @processed_datum" do
      processed_datum = ProcessedDatum.create! valid_attributes
      get :show, :id => processed_datum.id.to_s
      assigns(:processed_datum).should eq(processed_datum)
    end
  end

  describe "GET new" do
    it "assigns a new processed_datum as @processed_datum" do
      get :new
      assigns(:processed_datum).should be_a_new(ProcessedDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested processed_datum as @processed_datum" do
      processed_datum = ProcessedDatum.create! valid_attributes
      get :edit, :id => processed_datum.id.to_s
      assigns(:processed_datum).should eq(processed_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProcessedDatum" do
        expect {
          post :create, :processed_datum => valid_attributes
        }.to change(ProcessedDatum, :count).by(1)
      end

      it "assigns a newly created processed_datum as @processed_datum" do
        post :create, :processed_datum => valid_attributes
        assigns(:processed_datum).should be_a(ProcessedDatum)
        assigns(:processed_datum).should be_persisted
      end

      it "redirects to the created processed_datum" do
        post :create, :processed_datum => valid_attributes
        response.should redirect_to(ProcessedDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved processed_datum as @processed_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessedDatum.any_instance.stub(:save).and_return(false)
        post :create, :processed_datum => {}
        assigns(:processed_datum).should be_a_new(ProcessedDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessedDatum.any_instance.stub(:save).and_return(false)
        post :create, :processed_datum => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested processed_datum" do
        processed_datum = ProcessedDatum.create! valid_attributes
        # Assuming there are no other processed_data in the database, this
        # specifies that the ProcessedDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProcessedDatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => processed_datum.id, :processed_datum => {'these' => 'params'}
      end

      it "assigns the requested processed_datum as @processed_datum" do
        processed_datum = ProcessedDatum.create! valid_attributes
        put :update, :id => processed_datum.id, :processed_datum => valid_attributes
        assigns(:processed_datum).should eq(processed_datum)
      end

      it "redirects to the processed_datum" do
        processed_datum = ProcessedDatum.create! valid_attributes
        put :update, :id => processed_datum.id, :processed_datum => valid_attributes
        response.should redirect_to(processed_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the processed_datum as @processed_datum" do
        processed_datum = ProcessedDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessedDatum.any_instance.stub(:save).and_return(false)
        put :update, :id => processed_datum.id.to_s, :processed_datum => {}
        assigns(:processed_datum).should eq(processed_datum)
      end

      it "re-renders the 'edit' template" do
        processed_datum = ProcessedDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessedDatum.any_instance.stub(:save).and_return(false)
        put :update, :id => processed_datum.id.to_s, :processed_datum => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested processed_datum" do
      processed_datum = ProcessedDatum.create! valid_attributes
      expect {
        delete :destroy, :id => processed_datum.id.to_s
      }.to change(ProcessedDatum, :count).by(-1)
    end

    it "redirects to the processed_data list" do
      processed_datum = ProcessedDatum.create! valid_attributes
      delete :destroy, :id => processed_datum.id.to_s
      response.should redirect_to(processed_data_url)
    end
  end

end
